### ISSUE TITLE
Review deprecated fields change

### ISSUE THREAD

**Issue by tim-schilling** [aspiredu/moodle-local_aspiredu#11]
OpenLMS requires us to not use RAW fields in our plugin. The commit https://github.com/aspiredu/moodle-local_aspiredu/commit/6923e50bc186b79c30c7469b8d70766f7f2d696d was my attempt at removing them, but it requires a review of whether this will break based on the data that can be stored/fetched.

@guillogo if you can focus on this and #9 first as we need to have something ready before 3/21 at the latest.

**Comment by guillogo** [comment]
Hi @tim-schilling 

I've done a peer-review for the commit:

1. `settings.php`: secret and key are correct but I've changed the url params here https://github.com/aspiredu/moodle-local_aspiredu/commit/371e0b949e80b6a878b21c9dbf136633447412b9

2. `externallib.php`:

About the `PARAM_RAW` to `PARAM_CLEANHTML` changes, is not that simple, sometimes `PARAM_RAW` needs to be present as it depends on the base field. Do you have more info about why OpenLMS asked you to change all `externalib.php` `PARAM_RAW` or maybe they were talking about the setting page only? 

However, and the most important thing, is that I've noticed that the plugin overrides core external functions (some of those seems to be an exact copy no sure) that are now deprecated or have been deprecated long time ago, for instance:

**core:** get_grades (Deprecated since Moodle 3.2 more info: https://tracker.moodle.org/browse/MDL-51373)
**plugin:** core_grades_get_grades
 
**core:** get_forum_discussions_paginated (Deprecated since Moodle 3.7 more info: https://tracker.moodle.org/browse/MDL-66138)
**plugin:** mod_forum_get_forum_discussions_paginated

**core:** get_forum_discussion_posts (will be deprecated soon)
**plugin:** mod_forum_get_forum_discussion_posts

So, the correct approach in those particular cases seems to be to use the right core webservices instead of the ones that the plugin has overwritten, as the main reason to create custom webservices is if the ones that are there don't meet the requirements.

Thank you.

**Comment by tim-schilling** [comment]
> Do you have more info about why OpenLMS asked you to change all externalib.php PARAM_RAW or maybe they were talking about the setting page only?

They ran an automatic linter against the code base and it identified that PARAM_RAW and PARAM_RAW_TRIMMED were being used. There wasn't a person behind it.

**Comment by tim-schilling** [comment]
> However, and the most important thing, is that I've noticed that the plugin overrides core external functions (some of those seems to be an exact copy no sure) that are now deprecated or have been deprecated long time ago, ...

This is likely because we started supporting 2.4 and 2.7 as the major versions. Juan had to implement functions that weren't yet released in order to fetch all the data that we needed access to. It makes sense that they now look like duplicates and/or are being deprecated themselves.
